CREATE TABLE JOBBSOKERKOMPETANSE
(
  -- ID NUMBER GENERATED AS IDENTITY NOT NULL CONSTRAINT JOBBSOKERKOMPETANSE_PK PRIMARY KEY
  ID NUMBER NOT NULL,
  AKTOR_ID NVARCHAR2(255) NOT NULL,
  LAGRET_TIDSPUNKT TIMESTAMP(3) NOT NULL,
  BESVARELSE CLOB NOT NULL,
  RAAD CLOB NOT NULL,
  CONSTRAINT JOBBSOKERKOMPETANSE_PK PRIMARY KEY (ID)
--   CONSTRAINT ENSURE_JSON_BESVARELSE CHECK (BESVARELSE IS JSON),
--   CONSTRAINT ENSURE_JSON_RAD CHECK (RAD IS JSON)
);

CREATE SEQUENCE JOBBSOKERKOMPETANSE_ID_SEQ START WITH 1 INCREMENT BY 1;

CREATE INDEX JSK_AKTORID_IDX ON JOBBSOKERKOMPETANSE(AKTOR_ID);
