CREATE TABLE JOBBSOKERKOMPETANSE
(
  -- BESVARELSE_ID NUMBER GENERATED AS IDENTITY NOT NULL CONSTRAINT JOBBSOKERKOMPETANSE_PK PRIMARY KEY
  ID NUMBER NOT NULL,
  AKTOR_ID NVARCHAR2(255) NOT NULL,
  LAGRET_DATO TIMESTAMP(6) NOT NULL,
  BESVARELSE BLOB NOT NULL,
  RAAD BLOB NOT NULL,
  CONSTRAINT JOBBSOKERKOMPETANSE_PK PRIMARY KEY (ID)
--   CONSTRAINT ENSURE_JSON_BESVARELSE CHECK (BESVARELSE IS JSON),
--   CONSTRAINT ENSURE_JSON_RAD CHECK (RAD IS JSON)
);

CREATE SEQUENCE JOBBSOKERKOMPETANSE_ID_SEQ START WITH 1 INCREMENT BY 1;
