ALTER TABLE RAAD DROP COLUMN raad;
ALTER TABLE RAAD ADD raad_tittel NVARCHAR2(255);
ALTER TABLE RAAD ADD raad_ingress NVARCHAR2(255);

CREATE SEQUENCE AKTIVITET_SEQ START WITH 1;

CREATE TABLE AKTIVITET (
  aktivitet_id  NUMBER(19) NOT NULL,
  raad_id       NUMBER(19) NOT NULL,
  tittel        NVARCHAR2(255),
  innhold       NVARCHAR2(255),
  CONSTRAINT AKTIVITET_PK PRIMARY KEY (aktivitet_id),
  CONSTRAINT AKTIVITET_RAAD_FK FOREIGN KEY (raad_id) REFERENCES RAAD (raad_id)
);

CREATE INDEX AKTIVITET_RAAD_IDX
  ON AKTIVITET (raad_id);
