ALTER TABLE AKTIVITET DROP CONSTRAINT AKTIVITET_RAAD_FK;
ALTER TABLE RAAD DROP CONSTRAINT RAAD_BESVARELSE_FK;
ALTER TABLE SVARALTERNATIV DROP CONSTRAINT SVARALTERNATIV_SVAR_FK;
ALTER TABLE SVAR DROP CONSTRAINT SVAR_BESVARELSE_FK;

DROP TABLE BESVARELSE;
DROP TABLE SVAR;
DROP TABLE SVARALTERNATIV;
DROP TABLE RAAD;
DROP TABLE AKTIVITET;

DROP SEQUENCE BESVARELSE_SEQ;
DROP SEQUENCE SVAR_SEQ;
DROP SEQUENCE RAAD_SEQ;
DROP SEQUENCE SVARALTERNATIV_SEQ;
DROP SEQUENCE AKTIVITET_SEQ;


CREATE SEQUENCE KARTLEGGING_SEQ START WITH 1;
CREATE SEQUENCE BESVARELSE_SEQ START WITH 1;
CREATE SEQUENCE SVARALTERNATIV_SEQ START WITH 1;
CREATE SEQUENCE RAAD_SEQ START WITH 1;
CREATE SEQUENCE AKTIVITET_SEQ START WITH 1;


CREATE TABLE KARTLEGGING (
  kartlegging_id   NUMBER(19)     NOT NULL,
  aktor_id         NVARCHAR2(255) NOT NULL,
  under_oppfolging NUMBER(1, 0)   NOT NULL,
  kartlegging_dato TIMESTAMP(6)   NOT NULL,
  CONSTRAINT KARTLEGGING_PK PRIMARY KEY (kartlegging_id)
);

CREATE INDEX KARTLEGGING_AKTOR_ID_IDX
  ON KARTLEGGING (aktor_id);


CREATE TABLE BESVARELSE (
  besvarelse_id   NUMBER(19) NOT NULL,
  kartlegging_id  NUMBER(19) NOT NULL,
  sporsmal_key    NVARCHAR2(255),
  sporsmal        NVARCHAR2(255),
  tips_key        NVARCHAR2(255),
  tips            NVARCHAR2(255),
  CONSTRAINT BESVARELSE_PK PRIMARY KEY (besvarelse_id),
  CONSTRAINT BESVARELSE_KARTLEGGING_FK FOREIGN KEY (kartlegging_id) REFERENCES KARTLEGGING (kartlegging_id)
);

CREATE INDEX BESVARELSE_KARTLEGGING_IDX
  ON BESVARELSE (kartlegging_id);


CREATE TABLE SVARALTERNATIV (
  svaralternativ_id  NUMBER(19) NOT NULL,
  besvarelse_id      NUMBER(19) NOT NULL,
  svaralternativ_key NVARCHAR2(255),
  svaralternativ     NVARCHAR2(255),
  CONSTRAINT SVARALTERNATIV_PK PRIMARY KEY (svaralternativ_id),
  CONSTRAINT SVARALTERNATIV_BESVARELSE_FK FOREIGN KEY (besvarelse_id) REFERENCES BESVARELSE (besvarelse_id)
);

CREATE INDEX SVARALTERNATIV_BESVARELSE_IDX
  ON SVARALTERNATIV (besvarelse_id);


CREATE TABLE RAAD (
  raad_id         NUMBER(19) NOT NULL,
  kartlegging_id  NUMBER(19) NOT NULL,
  raad_key        NVARCHAR2(255),
  raad_tittel     NVARCHAR2(255),
  raad_ingress    NVARCHAR2(255),
  CONSTRAINT RAAD_PK PRIMARY KEY (raad_id),
  CONSTRAINT RAAD_KARTLEGGING_FK FOREIGN KEY (kartlegging_id) REFERENCES KARTLEGGING (kartlegging_id)
);

CREATE INDEX RAAD_KARTLEGGING_IDX
  ON RAAD (kartlegging_id);


CREATE TABLE AKTIVITET (
  aktivitet_id  NUMBER(19) NOT NULL,
  raad_id       NUMBER(19) NOT NULL,
  tittel        NVARCHAR2(255),
  innhold       CLOB,
  CONSTRAINT AKTIVITET_PK PRIMARY KEY (aktivitet_id),
  CONSTRAINT AKTIVITET_RAAD_FK FOREIGN KEY (raad_id) REFERENCES RAAD (raad_id)
);

CREATE INDEX AKTIVITET_RAAD_IDX
  ON AKTIVITET (raad_id);