CREATE SEQUENCE KULEPUNKT_SEQ START WITH 1;

CREATE TABLE KULEPUNKT (
  kulepunkt_id        NUMBER(19) NOT NULL,
  kartlegging_id      NUMBER(19) NOT NULL,
  kulepunkt_key       NVARCHAR2(255),
  kulepunkt_prioritet NUMBER(3),
  kulepunkt           NVARCHAR2(255),
  CONSTRAINT KULEPUNKT_PK PRIMARY KEY (kulepunkt_id),
  CONSTRAINT KULEPUNKT_KARTLEGGING_FK FOREIGN KEY (kartlegging_id) REFERENCES KARTLEGGING (kartlegging_id)
);

CREATE INDEX KULEPUNKT_KARTLEGGING_IDX
  ON KULEPUNKT (kartlegging_id);

-- ALTER TABLE KULEPUNKT DROP CONSTRAINT KULEPUNKT_KARTLEGGING_FK;
-- DROP TABLE KULEPUNKT;
-- DROP SEQUENCE KULEPUNKT_SEQ;