ALTER TABLE KARTLEGGING ADD oppsummering     NVARCHAR2(255);
ALTER TABLE KARTLEGGING ADD oppsummering_key NVARCHAR2(255);


-- ALTER TABLE KARTLEGGING DROP COLUMN oppsummering;
-- ALTER TABLE KARTLEGGING DROP COLUMN oppsummering_key;